// TETR.IO multiplayer rules: spin detection (All-Mini+) and attack calculation.
//
// Single source of truth for the player (versus.ts lock hook), the bot's
// search (ai.ts), bot move application (versus.ts), and the self-play harness.
// Geometry (corner counts, immobility) is measured by each caller on its own
// board representation; the rules that turn those measurements into a spin
// kind and an attack live here.
//
// Mirrors the engine logic in Triangle.js (github.com/halp1/triangle,
// src/engine/index.ts and utils/damageCalc), configured for Season 2
// multiplayer: All-Mini+ spins, multiplier combos, B2B charging (surge),
// garbage rounded down, no garbage multiplier.

import type { PieceType } from './types';

export type SpinKind = 0 | 1 | 2;
export const SPIN_NONE: SpinKind = 0;
export const SPIN_MINI: SpinKind = 1;
export const SPIN_FULL: SpinKind = 2;

export const RULES = {
  b2bBonus: 1,          // +1 per attack while B2B ≥ 1
  comboBonus: 0.25,     // attack × (1 + 0.25 × combo)
  comboMinifierLog: 1.25,
  surgeAt: 4,           // B2B level at which surge starts charging
  surgeBase: 3,         // surge sent when a B2B of exactly surgeAt breaks = surgeBase + 1
  allClearGarbage: 3,   // TODO: confirm for TETRA LEAGUE; 3 is the Quick Play value
  allClearB2b: 2,       // an all clear raises B2B by 2 instead of 1

  // Incoming garbage (TETR.IO multiplayer defaults)
  garbageCap: 8,           // most rows that can land from one lock
  garbageSpeedMs: 20 * 1000 / 60, // 20 frames of travel before an attack can land
  messinessChange: 1,      // chance the hole column moves between attacks
  messinessWithin: 0,      // chance it moves between rows of one attack
} as const;

// Base attack by lines cleared, indexed [lines]. Spins of 4+ lines use the
// T-spin quad/penta values whether mini or not, as TETR.IO does.
const BASE_NORMAL = [0, 0, 1, 2, 4, 5];
const BASE_MINI   = [0, 0, 1, 2, 10, 12];
const BASE_FULL   = [0, 2, 4, 6, 10, 12];

function baseAttack(lines: number, spin: SpinKind): number {
  if (lines <= 5) {
    return (spin === SPIN_FULL ? BASE_FULL : spin === SPIN_MINI ? BASE_MINI : BASE_NORMAL)[lines];
  }
  const extra = lines - 5;
  return spin ? BASE_FULL[5] + 2 * extra : BASE_NORMAL[5] + extra;
}

// ---- Spin detection ----

// The T's four bounding-box corners as [row, col] offsets, and which two of
// them the T faces in each rotation (0 = up, R, 2 = down, L).
export const T_CORNERS: ReadonlyArray<readonly [number, number]> = [[0, 0], [0, 2], [2, 0], [2, 2]];
export const T_FRONT_CORNERS: ReadonlyArray<readonly [number, number]> = [
  [0, 1], // up: top-left, top-right
  [1, 3], // right: top-right, bottom-right
  [2, 3], // down: bottom-left, bottom-right
  [0, 2], // left: top-left, bottom-left
];

// The "TST / fin" kick: a T rotated 90° from 0 or 2 into R or L using the last
// SRS test. It upgrades a corner T-spin mini to a full T-spin.
export function isTstKick(type: PieceType, delta: number, kickIndex: number, newRotation: number): boolean {
  return type === 'T' && (delta === 1 || delta === -1) && kickIndex === 4 && (newRotation & 1) === 1;
}

/**
 * Classify a placement under All-Mini+, given measurements taken on the final
 * position. Only placements whose last action was a rotation can spin.
 *
 * cornersFilled / frontCornersFilled: T corner counts (walls and floor count as
 *   filled); ignored for other pieces.
 * immobile: the piece cannot move left, right, up, or down.
 */
export function classifySpin(
  type: PieceType,
  rotatedLast: boolean,
  cornersFilled: number,
  frontCornersFilled: number,
  immobile: boolean,
  tstKick: boolean,
): SpinKind {
  if (!rotatedLast) return SPIN_NONE;
  let spin: SpinKind = SPIN_NONE;
  if (type === 'T' && cornersFilled >= 3) {
    spin = frontCornersFilled === 2 || tstKick ? SPIN_FULL : SPIN_MINI;
  }
  if (immobile && spin === SPIN_NONE) spin = SPIN_MINI;
  return spin;
}

// ---- Attack ----

export interface ClearResult {
  attack: number;   // total garbage generated by this lock, surge and all-clear included
  surge: number;    // part of `attack` released by breaking a charged B2B
  combo: number;    // combo after this lock (-1 = none)
  b2b: number;      // B2B level after this lock (-1 = none, 0 = first qualifying clear)
}

/**
 * Resolve one lock. `combo` and `b2b` are the levels before the lock
 * (-1 = none); `perfectClear` means the board is empty after the clear.
 */
export function resolveClear(
  combo: number,
  b2b: number,
  lines: number,
  spin: SpinKind,
  perfectClear: boolean,
): ClearResult {
  if (lines === 0) return { attack: 0, surge: 0, combo: -1, b2b };

  const nextCombo = combo + 1;
  const qualifies = spin !== SPIN_NONE || lines >= 4;
  let nextB2b: number;
  let brokeFrom = -1;
  if (perfectClear) nextB2b = b2b + RULES.allClearB2b;
  else if (qualifies) nextB2b = b2b + 1;
  else { brokeFrom = b2b; nextB2b = -1; }

  let garbage = baseAttack(lines, spin);
  if (nextB2b > 0) garbage += RULES.b2bBonus;
  if (nextCombo > 0) {
    garbage *= 1 + RULES.comboBonus * nextCombo;
    if (nextCombo > 1) garbage = Math.max(Math.log1p(nextCombo * RULES.comboMinifierLog), garbage);
  }

  let surge = 0;
  if (brokeFrom >= RULES.surgeAt) surge = brokeFrom - RULES.surgeAt + RULES.surgeBase + 1;

  const attack = Math.floor(garbage) + surge + (perfectClear ? RULES.allClearGarbage : 0);
  return { attack, surge, combo: nextCombo, b2b: nextB2b };
}

/** Short label for a clear, e.g. "TSD", "T-Spin Mini Single", "S-Spin Double". */
export function clearLabel(type: PieceType, lines: number, spin: SpinKind, perfectClear: boolean): string {
  if (perfectClear) return 'PC';
  const count = ['', 'Single', 'Double', 'Triple', 'Quad'][Math.min(lines, 4)];
  if (spin === SPIN_FULL && type === 'T') return ['TS', 'TSS', 'TSD', 'TST', 'TSQ'][Math.min(lines, 4)];
  if (spin === SPIN_MINI) return `${type}-Spin Mini${count ? ' ' + count : ''}`;
  if (spin === SPIN_FULL) return `${type}-Spin${count ? ' ' + count : ''}`;
  return count === 'Quad' ? 'Quad' : count;
}
