"""
Train the CNN position evaluator on supervised data generated by generate_data.py.

The model learns to predict normalized game outcome (final_lines / 40) from a
binary 20×10 board afterstate. After training, the best checkpoint is saved to
models/tetris_eval.pt for use by export_onnx.py.

Usage:
    python train.py [--data data/positions.npz] [--epochs 100] [--batch-size 512]
                    [--lr 1e-3] [--out models/tetris_eval.pt]
"""

import argparse
import os
import numpy as np
import torch
import torch.nn as nn
from torch.utils.data import DataLoader, TensorDataset, random_split


# ---- Model ----

class TetrisCNN(nn.Module):
    """
    Small CNN for scoring Tetris board afterstates.

    Input:  (B, 1, 20, 10) float32 binary occupancy
    Output: (B, 1) float32 scalar value (higher = better position)
    """

    def __init__(self):
        super().__init__()
        self.conv = nn.Sequential(
            nn.Conv2d(1, 32, kernel_size=3, padding=1),
            nn.BatchNorm2d(32),
            nn.ReLU(),
            nn.Conv2d(32, 64, kernel_size=3, padding=1),
            nn.BatchNorm2d(64),
            nn.ReLU(),
            nn.Conv2d(64, 32, kernel_size=3, padding=1),
            nn.BatchNorm2d(32),
            nn.ReLU(),
            nn.AdaptiveAvgPool2d(1),  # → (B, 32, 1, 1)
        )
        self.fc = nn.Sequential(
            nn.Flatten(),
            nn.Linear(32, 64),
            nn.ReLU(),
            nn.Linear(64, 1),
        )

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        return self.fc(self.conv(x))


# ---- Training loop ----

def train(args):
    os.makedirs(os.path.dirname(args.out), exist_ok=True)

    # Load data
    data = np.load(args.data)
    boards = data['boards']  # (N, 20, 10)
    values = data['values']  # (N,)
    print(f'Loaded {len(boards)} positions from {args.data}')

    boards_t = torch.tensor(boards[:, None, :, :], dtype=torch.float32)  # (N, 1, 20, 10)
    values_t = torch.tensor(values[:, None],        dtype=torch.float32)  # (N, 1)

    dataset = TensorDataset(boards_t, values_t)
    val_size = max(1, int(0.1 * len(dataset)))
    train_size = len(dataset) - val_size
    train_ds, val_ds = random_split(dataset, [train_size, val_size],
                                    generator=torch.Generator().manual_seed(42))

    train_loader = DataLoader(train_ds, batch_size=args.batch_size, shuffle=True,
                              num_workers=0, pin_memory=True)
    val_loader   = DataLoader(val_ds,   batch_size=args.batch_size * 4, shuffle=False,
                              num_workers=0)

    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
    print(f'Training on {device}')

    model = TetrisCNN().to(device)
    n_params = sum(p.numel() for p in model.parameters())
    print(f'Model parameters: {n_params:,}')

    optimizer = torch.optim.Adam(model.parameters(), lr=args.lr, weight_decay=1e-4)
    scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=args.epochs)
    criterion = nn.MSELoss()

    best_val_loss = float('inf')
    patience = 10
    no_improve = 0

    for epoch in range(1, args.epochs + 1):
        # Train
        model.train()
        train_loss = 0.0
        for x, y in train_loader:
            x, y = x.to(device), y.to(device)
            optimizer.zero_grad()
            pred = model(x)
            loss = criterion(pred, y)
            loss.backward()
            optimizer.step()
            train_loss += loss.item() * len(x)
        train_loss /= train_size
        scheduler.step()

        # Validate
        model.eval()
        val_loss = 0.0
        with torch.no_grad():
            for x, y in val_loader:
                x, y = x.to(device), y.to(device)
                val_loss += criterion(model(x), y).item() * len(x)
        val_loss /= val_size

        if epoch % 10 == 0 or epoch == 1:
            print(f'Epoch {epoch:3d}/{args.epochs}  '
                  f'train_loss={train_loss:.5f}  val_loss={val_loss:.5f}  '
                  f'lr={scheduler.get_last_lr()[0]:.2e}')

        if val_loss < best_val_loss:
            best_val_loss = val_loss
            torch.save(model.state_dict(), args.out)
            no_improve = 0
        else:
            no_improve += 1
            if no_improve >= patience:
                print(f'Early stopping at epoch {epoch} (no improvement for {patience} epochs)')
                break

    print(f'\nBest val_loss: {best_val_loss:.5f}')
    print(f'Model saved to {args.out}')


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--data',       default='data/positions.npz')
    parser.add_argument('--epochs',     type=int,   default=100)
    parser.add_argument('--batch-size', type=int,   default=512)
    parser.add_argument('--lr',         type=float, default=1e-3)
    parser.add_argument('--out',        default='models/tetris_eval.pt')
    args = parser.parse_args()
    train(args)


if __name__ == '__main__':
    main()
